ckpt_dir: "/home/kieron/fyp/blt/hf-weights/blt_1b"
dump_dir: "/home/kieron/fyp/blt/dump-dir"
entropy_ckpt_dir: "/home/kieron/fyp/blt/hf-weights/entropy_model"
generator:
  max_tokens: 2048
  dtype: bf16
  temperature: 0.0
  top_p: 0.95
harness:
  tasks:
    # - hellaswag
    # - piqa
    # - arc_easy
    # - arc_challenge
    - mmlu
    # - mbpp
    # - humaneval